### PR TITLE
Adding a z!justask command. 

### PR DESCRIPTION
**Pull request by Tirithel**
Please review the change, I haven't used this library and couldn't test because I don't have the os.env variables :)

Thanks.

### CODE REVIEW

**Review by yagomichalak — COMMENTED** [review]
I don't really see why this deserves a cog just for itself, considering that the command is not just related to programming.

**Comment by Tirithel** [comment]
Should I move it to misc then? :)

**Comment by yagomichalak** [comment]
Yes, please.

**Comment by Tirithel** [comment]
Cog deleted, contents moved to misc.

**Pull request merged**
